$(function() {
  var pdfMaker = new cartaParaPdf.PdfMaker();
  var orgao = '<orgao xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><url>http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/304</url><nome>Ministério da Saúde</nome><conteudo><![CDATA[Órgão do governo federal responsável pela promoção, proteção e recuperação da saúde da população, reduzindo as enfermidades, controlando as doenças endêmicas e parasitárias e melhorando a vigilância à saúde. \n\nDentre os serviços ofertados ao público estão o [cartão SUS](/servico/cartao-sus) e o [SAMU - Serviço de Atendimento Móvel de Urgência](/servico/samu-servico-de-atendimento-movel-de-urgencia).]]></conteudo></orgao>';
  var servicos = [
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?> <servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd"> <nome>Centro de Testagem e Acolhimento (CTA) - DST/AIDS</nome> <sigla/> <nomes-populares/> <descricao>Os Centros de Testagem e Aconselhamento (CTA) são serviços de saúde que realizam ações de diagnóstico e prevenção de doenças sexualmente transmissíveis. Nesses serviços, é possível realizar testes para HIV, sífilis e hepatites B e C gratuitamente. Todos os testes são realizados de acordo com a norma definida pelo Ministério da Saúde e com produtos registrados na Agência Nacional de Vigilância Sanitária (Anvisa) e por ela controlados. * [Mais informações](http://www.aids.gov.br/): Portal sobre aids, doenças sexualmente transmissíveis e hepatites virais</descricao> <gratuito/> <solicitantes/> <tempo-total-estimado> <descricao/> </tempo-total-estimado> <etapas> <etapa> <titulo/> <descricao/> <documentos> <default/> </documentos> <custos> <default/> </custos> <canais-de-prestacao> <default> <canal-de-prestacao tipo="web"> <descricao>http://www.aids.gov.br/pagina/servicos-de-saude</descricao> </canal-de-prestacao> </default> </canais-de-prestacao> </etapa> </etapas> <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/304"/> <segmentos-da-sociedade> <item>Cidadãos</item> </segmentos-da-sociedade> <areas-de-interesse> <item>Saúde</item> </areas-de-interesse> <palavras-chave/> <legislacoes/> </servico>'
  ];

  $('#pdf').click(function() {
    pdfMaker.geraPdf(orgao, servicos);
  });
});
