$(function() {
  var pdfMaker = new cartaParaPdf.PdfMaker();
  var orgao = '<?xml version="1.0" encoding="UTF-8" standalone="no"?><orgao xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">    <url>http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/89</url>    <nome>Banco Central do Brasil (BACEN)</nome>    <conteudo><![CDATA[Autarquia federal vinculada ao [Ministério da Fazenda], tem por finalidade:* a formulação, a execução, o acompanhamento e o controle das políticas monetária, cambial, de crédito e de relações financeiras com o exterior;* a organização, disciplina e fiscalização do Sistema Financeiro Nacional (SFN) e do Sistema de Consórcio; e* a gestão do Sistema de Pagamentos Brasileiro (SPB) e dos serviços do meio circulante.Dentre os serviços ofertados ao público estão [ranking de Instituições por Índice de Reclamações](/servico/ranking-das-instituicoes-financeiras-mais-reclamadas); [emissão de certidão negativa do Banco Central](/servico/emissao-de-certidao-negativa-do-banco-central) e a [calculadora cidadão](/servico/calculadora-do-cidadao).[Ministério da Fazenda]:/orgao/ministerio-da-fazenda-mf]]></conteudo>    <contato><![CDATA[[Ouvidoria](http://www.ouvidorias.gov.br/cidadao/lista-de-ouvidorias/bancos/banco-central-do-brasil-bacen)[Site Oficial](http://www.bcb.gov.br/)]]></contato></orgao>';
  var servicos = [
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?><servico xmlns="http://servicos.gov.br/v3/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/v3/schema ../servico.xsd">    <nome>Calculadora do Cidadão</nome>    <sigla/>    <nomes-populares/>    <descricao>Ferramenta on-line que ajuda o cidadão a calcular:O custo de um financiamento com prestações fixas;O valor, no futuro, do dinheiro investido hoje;Quanto o cidadão terá, no futuro, se economizar, todo mês, uma parcela da renda;Quanto vale hoje, corrigido pela inflação, o dinheiro utilizado no passado.* [Outros](https://itunes.apple.com/us/app/calculadora-do-cidadao/id562324722?l=pt&amp;ls=1&amp;mt=8): Página da Calculadora do Cidadão na App Store* [Outros](http://play.google.com/store/apps/details?id=br.gov.bcb.mobile.android.calculadoracidadao): Página da Calculadora do Cidadão na Google Play</descricao>    <gratuito/>    <solicitantes/>    <tempo-total-estimado>        <descricao/>    </tempo-total-estimado>    <etapas>        <etapa>            <titulo/>            <descricao/>            <documentos>                <default/>            </documentos>            <custos>                <default/>            </custos>            <canais-de-prestacao>                <default>                    <canal-de-prestacao tipo="web">                        <descricao>http://www.bcb.gov.br/?calculadora</descricao>                    </canal-de-prestacao>                </default>            </canais-de-prestacao>        </etapa>    </etapas>    <orgao id="http://estruturaorganizacional.dados.gov.br/id/unidade-organizacional/89"/>    <segmentos-da-sociedade>        <item>Cidadãos</item>        <item>Empresas</item>    </segmentos-da-sociedade>    <areas-de-interesse>        <item>Economia e Finanças</item>    </areas-de-interesse>    <palavras-chave/>    <legislacoes/></servico>'
  ];

  $('#pdf').click(function() {
    pdfMaker.geraPdf(orgao, servicos);
  });
});
